name: PullRequest

on: [pull_request]

jobs:
  build-objective-git:
    name: Build objective-git
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_12.2.app
      - name: Build project
        run: set -o pipefail && xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" build | xcpretty

