name: Build & Test Pull Request

on: [pull_request]

shared: &shared
  runs-on: macOS-latest
  strategy:
    fail-fast: false
    matrix:
      xcode: [Xcode_11.7, Xcode_12.2, Xcode_12.4]

jobs:
  build-mac:
    <<: *shared
    name: Build Objective-Git (Mac)
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: Build project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" build | xcpretty
      - name: Test project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" test | xcpretty

  build-ios:
    <<: *shared
    name: Build Objective-Git (iOS)
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: Build project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit iOS" build | xcpretty
      - name: Test project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit iOS" test | xcpretty

