name: PullRequest

on: [pull_request]

jobs:
  build-objective-git:
    name: Build objective-git
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: [Xcode_11.7, Xcode_12.2, Xcode_12.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: Build project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" archive | xcpretty

