name: Build & Test

on: [pull_request]

jobs:
  build-mac:
    name: ${{ matrix.scheme }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: [Xcode_10.3, Xcode_11.7, Xcode_12.4]
        scheme: ['ObjectiveGit Mac', 'ObjectiveGit iOS']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: Build project
        run: SCHEME="${{ matrix.scheme }}" ./script/cibuild
