name: Build & Test

on: [pull_request]

jobs:
  build-mac:
    name: Objective-Git (Mac)
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: [Xcode_11.7, Xcode_12.2, Xcode_12.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: Build project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" build
      - name: Test project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" test

  build-ios:
    name: Objective-Git (iOS)
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: [Xcode_11.7, Xcode_12.2, Xcode_12.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: Build project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit iOS" build
      - name: Test project
        run: xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit iOS" test

